### ISSUE TITLE
-Wall issue

### ISSUE THREAD

**Issue by tyndev** [krixi/c-lab-grader#1]
When i compile my lab2 code with -Wall the error i get has to do with C99 initial declarations. The grader is giving me a 1/2 in my first section because of this. Am I not able to compile in C99?

Also, I am getting a 0/2 for the output section. Do my outputs need to be word for word what you use? For instance, when I ask the user for the input values I ask: `Enter value 1 >` and `Enter value 2 >` up to the number of inputs they declared. Is this my issue here?

**Comment by krixi** [comment]
To use the C99 standards, you have two options: you can either compile the file using the `c99` alias, or with the flag `-std=c99`. This is required if you want to initialize the loop variable inside the for loop, e.g. 

```
for( int i = 0; i < n; ++i )
```

For the output section, your print statements must exactly match, down to the character. So that is probably your issue there.

**Comment by tyndev** [comment]
Thanks for the response. I figured out my problem with the compiler issue. But I am still getting zero on the output section even though they match exactly. I've double checked them a couple times am pretty certain that they are the same. Could there be another problem?

**Comment by krixi** [comment]
When you run the program, it will produce an output folder with a couple of files in it. Open the .out file with a text editor and you'll be able to see the output of the Linux `diff` command,  comparing your program's output and the expected output. 

Lines that begin with a - indicate something was removed, and lines that begin with a + mean something was added on that line. If it looks like the same line appears twice, with both a - and +, then something on that line doesn't quite match.
