### ISSUE TITLE
Formatting errors

### ISSUE THREAD

**Issue by bensss** [krixi/c-lab-grader#3]
The grader tool is saying there are formatting errors, my output in putty matches the output on the web-sight exactly.  when I go to test0.diff file the two lines are the same accept for differing number of spaces between the input prompts.  The number of spaces is correct in the putty output and seems different in the grader than the putty output.  I also had this same issue with the previous lab.  not sure what I'm missing.  I attached screen shots of putty output and test0.diff if that helps explain my problem. 
<img width="436" alt="putty output" src="https://cloud.githubusercontent.com/assets/17537784/13385332/bf91c0bc-de5c-11e5-9441-86b3104b6fc5.png">
![grader output](https://cloud.githubusercontent.com/assets/17537784/13385333/bf95aa10-de5c-11e5-8811-775c4d33669e.jpg)

**Comment by krixi** [comment]
Use the tab control character \t instead of spaces

**Comment by bensss** [comment]
Great, thanks a bunch!
